defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- assets/css/style.css
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

url: "https://redtide.github.io/dev-docs"

organization:
  name: "Dev Docs"
  url: "https://redtide.github.io/dev-docs"

repository:
  branch: "master"
  url: "https://github.com/redtide/dev-docs"

locale:
  default: "en"

authors:
  content: "RedTide"
  web: "RedTide"

spdx_license_id: "MPL-2.0"
