defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Gemfile
- Gemfile.lock
- LICENSE
- new_post
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- assets/css/style.css
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

url: "https://redtide.github.io/dev-docs"

spdx_license_id: "MPL-2.0"

organization:
  name: "Dev Docs"
  url: "https://github.com/redtide/dev-docs"

authors:
  content: "RedTide"
  web: "RedTide"

google:
  analytics_code:
  cse_code:

disqus_shortname:
